### ISSUE TITLE
why not use a custom sort function?

### ISSUE THREAD

**Issue by jfilter** [derhuerst/sort-array-by-another#1]
```js
const zipped = items.map((x, i) => [model[i], x])
const zippedSorted = zipped.sort((x, y) => x[0] > y[0]);
const sorted = zippedSorted.map(x => x[1])
```

**Comment by derhuerst** [comment]
[This is what it does](https://github.com/derhuerst/sort-array-by-another/blob/17b6bfbcd8d02f6bf0910b6635250fa036201f1b/index.js#L7-L11), just with slightly faster `for` loops. I'm not sure if this is the fastest way to do it though.

FYI: The whole module is simple, but I wanted to move it into a library so that, in the future, I don't have to type this anymore.

**Comment by derhuerst** [comment]
If you have a faster and/or GC-friendlier version in mind, let me know!

**Comment by jfilter** [comment]
Okay, but why is it so important to 'record' the sorting? You could just return the sorted items.

**Comment by derhuerst** [comment]
That's what `apply` does. It returns the sort array of items. "Record" is a very fancy word for generating an array (called `map` in my code) with the supposed position for each item.

**Comment by derhuerst** [comment]
I guess I've written the readme with my specific problem in mind, so it's very biased. How would you describe the problem it solves?

**Comment by jfilter** [comment]
I guess you have multiple arrays of _items_. So each array contains attributes of the items. And you only want to do the sorting once and _apply_ it to all the attributes.

**Comment by derhuerst** [comment]
> So each array contains attributes of the items.

Technically not always, but the most common use case is probably what you describe. 👍

> And you only want to do the sorting once and apply it to all the attributes.

True and certainly *one* argument/phrasing. Another, which is what I tried to convey in [the current readme](https://github.com/derhuerst/sort-array-by-another/blob/17b6bfbcd8d02f6bf0910b6635250fa036201f1b/readme.md#usage): Sometimes you can't sort the array, but know the order implicitly from another array.

Let's use your proposal, I think it is more intuitive.
